
name: 'Backslash scan'
description: 'Scan your application with backslash'

inputs:
  authToken:
    description: 'Backslash autherization token'
    required: true
    default: ''
  ignoreBlock:
    description: 'Ignore pipeline blocking findings?'
    type: boolean
    required: true
    default: false
  prScan:
    description: 'If set to true, the scan will return only findings new to the pr otherwise the scan will return all findings'
    required: false
    type: boolean
    default: false
  isOnPremise:
    description: 'Wether or not the action is being run on a github-on-premise instance'
    required: false
    type: boolean
    default: false
  disablePrComments:
    description: 'Disable pr comments'
    required: false
    type: boolean
    default: false
  githubToken:
    description: 'Github auth token'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'