# In TypeScript actions, `dist/` is a special directory. When you reference
# an action with the `uses:` property, `dist/index.js` is the code that will be
# run. For this project, the `dist/index.js` file is transpiled from other
# source files. This workflow ensures the `dist/` directory contains the
# expected transpiled code.
#
# If this workflow is run from a feature branch, it will act as an additional CI
# check and fail if the checked-in `dist/` directory does not match what is
# expected from the build.
name: Check Transpiled JavaScript

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check-dist:
    name: Check dist/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        id: install
        run: npm i && npm i -g @vercel/ncc

      - name: Build and push
        id: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Determine the correct branch name
          if [ "$GITHUB_HEAD_REF" != "" ]; then
            branch_name="$GITHUB_HEAD_REF"
          else
            branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          fi
          echo "Detected branch: $branch_name"
          git checkout "$branch_name"
          npm run build
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git add dist/
            git commit -m "Build: Update dist/ directory"
            git push
          fi