name: CI Scanner

on:
  pull_request:
    branches:
      - main

env:
  API_KEY: ${{ secrets.BACKSLASH_API_KEY }}


jobs:
  backslash_scan_job:
    name: Backslash scan
    runs-on: ubuntu-latest
    steps:
      - name: Backslash scan step
        uses: backslash-security/scan-action@main
        with:
          authToken: ${{ env.API_KEY }}
          prScan: true
          disablePrComments: false
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          localExport: true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: Backslash-report
          path: Backslash-scan-results/
          retention-days: 10
